version: '2'
services:
 
  core:
    container_name: appcore
    build: ./core
    image:  ejb-core 
    ports: 
      - "8081:8080"
      - "1098:1099"
      - "1097:1098"
      - "3874:3873"
      - "3701:3700" 
      - "8182:8181"
      - "8010:8009"
  
  web:
    container_name:  appjsf
    build: ./jsf
    image:  ejb-jsf
    ports: 
     - "8082:8080"
    links: 
     - "core:host-core"
