/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.jse;

import br.edu.ifpb.shared.MensagemSingoton;
import br.edu.ifpb.shared.ServiceLocator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */
public class Mensagens extends javax.swing.JFrame {

    /**
     * Creates new form Mensagens
     */
     private static MensagemSingoton MS;
     private ServiceLocator locator;
    public Mensagens() {
       
        initComponents();
        locator = new ServiceLocator();
        MS =locator.lookup("java:global/core/SalaDeBatePapo", MensagemSingoton.class);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mensagens = new javax.swing.JTable();
        JBmsgAtualizar = new javax.swing.JButton();
        JBAdd = new javax.swing.JButton();
        jTMsg = new javax.swing.JTextField();
        jBRemove = new javax.swing.JButton();

        mensagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mensagens.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(mensagens);
        mensagens.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        JBmsgAtualizar.setText("Atualizar");
        JBmsgAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmsgAtualizarActionPerformed(evt);
            }
        });

        JBAdd.setText("Add");
        JBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAddActionPerformed(evt);
            }
        });

        jTMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMsgActionPerformed(evt);
            }
        });

        jBRemove.setText("Remove");
        jBRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBRemove)
                        .addGap(18, 18, 18)
                        .addComponent(JBmsgAtualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBAdd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBmsgAtualizar)
                    .addComponent(jBRemove))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBmsgAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmsgAtualizarActionPerformed
        // TODO add your handling code here:
        init();
       
    }//GEN-LAST:event_JBmsgAtualizarActionPerformed

    private void JBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAddActionPerformed
        // TODO add your handling code here:
        MS.add(jTMsg.getText());
        init();
    }//GEN-LAST:event_JBAddActionPerformed

    private void jTMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMsgActionPerformed

    private void jBRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoveActionPerformed
        // TODO add your handling code here:
         String mensagem;
        mensagem = String.valueOf(mensagens.getModel()
                .getValueAt(mensagens.getSelectedRow(),
                         mensagens.getSelectedColumn()));
        MS.remover(mensagem);
     init();
    }//GEN-LAST:event_jBRemoveActionPerformed
private void init(){
      limpaTabela();
        DefaultTableModel val = (DefaultTableModel) mensagens.getModel();
       
for (String elem : MS.historico()) {
             val.addRow(new String[]{elem});
        }
       
         
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdd;
    private javax.swing.JButton JBmsgAtualizar;
    private javax.swing.JButton jBRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTMsg;
    private javax.swing.JTable mensagens;
    // End of variables declaration//GEN-END:variables

    private void limpaTabela() {
        DefaultTableModel val = (DefaultTableModel) mensagens.getModel();
    // produtos.removeAll();
		int size = val.getRowCount();
                
		for(int i = 0; i < size; i++) {
			val.removeRow(i);
		}
    }
}

